/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.example.cooklog.cook'

type $nsid = typeof $nsid

export { $nsid }

/** A meal the author cooked, with photos. */
type Main = {
  $type: 'com.example.cooklog.cook'

  /**
   * What was cooked.
   */
  dishName: string

  /**
   * Kind of meal. Clients should display unrecognised values as 'Other'.
   */
  mealType:
    | 'breakfast'
    | 'lunch'
    | 'dinner'
    | 'snack'
    | 'bread'
    | 'dessert'
    | l.UnknownString

  /**
   * Optional free-text note about the cook.
   */
  note?: string

  /**
   * Photos of the cook, in display order.
   */
  images: Image[]

  /**
   * When the meal was cooked, in the author's local time with its UTC offset.
   */
  cookedAt: l.DatetimeString

  /**
   * When this record was created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A meal the author cooked, with photos. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    dishName: /*#__PURE__*/ l.string({
      minGraphemes: 1,
      maxGraphemes: 100,
      maxLength: 1000,
    }),
    mealType: /*#__PURE__*/ l.string<{
      knownValues: ['breakfast', 'lunch', 'dinner', 'snack', 'bread', 'dessert']
      maxLength: 64
    }>({ maxLength: 64 }),
    note: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 1000, maxLength: 10000 }),
    ),
    images: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<Image>((() => image) as any),
      { minLength: 1, maxLength: 4 },
    ),
    cookedAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Image = {
  $type?: 'com.example.cooklog.cook#image'
  image: l.BlobRef

  /**
   * Alt text describing the photo.
   */
  alt?: string
  aspectRatio: AspectRatio
}

export type { Image }

const image = /*#__PURE__*/ l.typedObject<Image>(
  $nsid,
  'image',
  /*#__PURE__*/ l.object({
    image: /*#__PURE__*/ l.blob({
      accept: ['image/jpeg', 'image/webp'],
      maxSize: 1000000,
    }),
    alt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 300, maxLength: 3000 }),
    ),
    aspectRatio: /*#__PURE__*/ l.ref<AspectRatio>((() => aspectRatio) as any),
  }),
)

export { image }

/** Width and height of the image, used to reserve layout space before it loads. Only the ratio matters. */
type AspectRatio = {
  $type?: 'com.example.cooklog.cook#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

/** Width and height of the image, used to reserve layout space before it loads. Only the ratio matters. */
const aspectRatio = /*#__PURE__*/ l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  /*#__PURE__*/ l.object({
    width: /*#__PURE__*/ l.integer({ minimum: 1 }),
    height: /*#__PURE__*/ l.integer({ minimum: 1 }),
  }),
)

export { aspectRatio }
