import { NextRequest, NextResponse } from "next/server";
import { Client, jsonToLex, l } from "@atproto/lex";
import { isValidTid } from "@atproto/syntax";
import { getSession } from "@/lib/auth/session";
import { COLLECTIONS } from "@/lib/config";
import { MEAL_TYPES } from "@/lib/cook/mealTypes";
import { getDb } from "@/lib/db";
import { cookUriOf } from "@/lib/db/queries";
import { readJson } from "@/lib/http";
import { ensureAccount } from "@/lib/indexer/account";
import { cookRow, upsertCook } from "@/lib/indexer/cook";
import { cook } from "@/lib/lexicons";
import { deleteOwnRecord } from "@/lib/social/write";

type Body = {
  rkey?: unknown;
  dishName?: unknown;
  mealType?: unknown;
  note?: unknown;
  cookedAt?: unknown;
  images?: { blob?: unknown; alt?: unknown; width?: unknown; height?: unknown }[];
};

const str = (v: unknown) => (typeof v === "string" ? v.trim() : "");

// Creates the cook record on the user's PDS, then upserts it into the index
// (read-your-own-writes, §3) so it shows up before Tap delivers it.
//
// `rkey` is a TID generated by the client once per post, and reused on
// retry. If the first attempt reached the PDS but the response was lost
// (e.g. the PWA was suspended), the retry finds the existing record instead
// of posting a duplicate.
export async function POST(request: NextRequest) {
  const session = await getSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: Body;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const rkey = str(body.rkey);
  if (!isValidTid(rkey)) {
    return NextResponse.json({ error: "Invalid rkey" }, { status: 400 });
  }

  // The Lexicon accepts any mealType (other clients may add values), but
  // this app only writes the known ones; that also rules out "".
  const mealType = str(body.mealType);
  if (!MEAL_TYPES.some((m) => m.value === mealType)) {
    return NextResponse.json({ error: "Invalid mealType" }, { status: 400 });
  }

  const note = str(body.note);
  const recordJson = {
    $type: COLLECTIONS.cook,
    dishName: str(body.dishName),
    mealType,
    ...(note ? { note } : {}),
    images: (Array.isArray(body.images) ? body.images : []).map((img) => {
      const alt = str(img?.alt);
      return {
        image: img?.blob,
        ...(alt ? { alt } : {}),
        aspectRatio: { width: img?.width, height: img?.height },
      };
    }),
    cookedAt: str(body.cookedAt),
    createdAt: l.currentDatetimeString(),
  };

  // Enforce every §4 limit here too, before anything reaches the PDS.
  let record: cook.Main;
  try {
    record = cook.$parse(jsonToLex(recordJson as never));
  } catch (err) {
    return NextResponse.json(
      { error: `Invalid cook: ${err instanceof Error ? err.message : err}` },
      { status: 400 },
    );
  }

  const client = new Client(session);
  let uri: string;
  let cid: string;
  try {
    ({ uri, cid } = await client.create(cook, record, { rkey }));
  } catch (err) {
    const existing = await client.get(cook, { rkey }).catch(() => null);
    if (!existing) {
      console.error("createRecord failed", err);
      return NextResponse.json(
        { error: "Posting to your PDS failed" },
        { status: 502 },
      );
    }
    // An earlier attempt with this rkey already landed.
    ({ uri, cid } = existing as { uri: string; cid: string });
    record = existing.value;
  }

  // The post is on the PDS either way; if this fails, Tap indexes it later.
  try {
    // Feeds join on account; Tap's identity event fills in the handle.
    await ensureAccount(getDb(), session.did);
    await upsertCook(getDb(), cookRow({ uri, cid, authorDid: session.did, record }));
  } catch (err) {
    console.error("read-your-own-writes upsert failed", uri, err);
  }

  return NextResponse.json({ uri, cid });
}

// DELETE { rkey } — delete one of your own cooks (§6.6). Its photos stop
// being served at once (the image proxy only serves indexed cooks), and the
// PDS garbage-collects the blobs. Kudos and comments others left on it stay
// in their repos and in the index, hidden (§6.2).
export async function DELETE(request: NextRequest) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const rkey = (await readJson(request))?.rkey;
  if (typeof rkey !== "string" || !isValidTid(rkey)) {
    return NextResponse.json({ error: "Invalid rkey" }, { status: 400 });
  }
  const uri = cookUriOf(session.did, rkey);
  try {
    await deleteOwnRecord(new Client(session), getDb(), "cook", uri);
    return NextResponse.json({ deleted: uri });
  } catch (err) {
    console.error("cook delete failed", err);
    return NextResponse.json({ error: "Deleting your cook failed on your PDS" }, { status: 502 });
  }
}
